name: cricshot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - pip:
    - transformers
    - datasets
    - evaluate
    - imageio
    - huggingface-hub 
    - git+https://github.com/facebookresearch/pytorchvideo
    - accelerate>=0.26.0
    - scikit-learn
    - python-dotenv
    - sentencepiece
    - protobuf